# Generated by Django 2.1.5 on 2021-06-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_emp_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('fname', models.CharField(max_length=20, unique=True)),
                ('lname', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=20)),
                ('iname', models.CharField(max_length=30, unique=True)),
                ('comment', models.TextField(max_length=300)),
            ],
        ),
    ]
