# Generated by Django 2.1.5 on 2021-06-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='iname',
            field=models.CharField(max_length=30),
        ),
    ]
