# Generated by Django 2.1.5 on 2021-06-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210609_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='contact',
            new_name='profession',
        ),
    ]
